# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0002_auto_20160129_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='washRequest',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='a.WashRequest'),
        ),
    ]
