# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0003_address_washrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=10)),
                ('washRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.WashRequest')),
            ],
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='street_address',
        ),
    ]
