# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0004_auto_20160130_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='washrequest',
            name='description',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='washrequest',
            name='discount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='washrequest',
            name='electricity_details',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='washrequest',
            name='total_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='washrequest',
            name='vacuum_details',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='washrequest',
            name='wash_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 30, 8, 59, 36, 474909, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='washrequest',
            name='water_details',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_plate',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
