# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0005_auto_20160130_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='role',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
