# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0007_auto_20160131_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dirtiness',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
