# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0008_car_dirtiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washrequest',
            name='assigned_washer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a.Washer'),
        ),
        migrations.AlterField(
            model_name='washrequest',
            name='washee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a.Washee'),
        ),
    ]
