# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0009_auto_20160202_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='oneline_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='suburb',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
