# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0011_auto_20160202_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washrequest',
            name='wash_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
