# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0012_auto_20160202_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dirtiness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_plate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
