# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0015_auto_20160202_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='washrequest',
            name='vacuum',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='washrequest',
            name='wiping',
            field=models.BooleanField(default=True),
        ),
    ]
