# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0016_auto_20160202_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='washrequest',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
