# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0017_washrequest_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='washrequest',
            name='extra_dirty',
            field=models.BooleanField(default=False),
        ),
    ]
