# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0019_auto_20160205_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washrequest',
            name='extra_dirty',
        ),
        migrations.RemoveField(
            model_name='washrequest',
            name='vacuum',
        ),
        migrations.RemoveField(
            model_name='washrequest',
            name='wiping',
        ),
        migrations.AddField(
            model_name='car',
            name='extra_dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='specs',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='vacuum',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='wiping',
            field=models.BooleanField(default=True),
        ),
    ]
