# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0020_auto_20160205_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
