# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0021_auto_20160205_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='washRequest',
        ),
        migrations.AddField(
            model_name='washrequest',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a.Address'),
        ),
    ]
