# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0022_auto_20160208_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
