# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0024_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='washrequest',
            name='car_count',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
