# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('socialaccount', '0002_token_max_lengths'),
        ('account', '0002_email_max_length'),
        ('a', '0026_auto_20160215_1222'),
    ]

    operations = [
    ]
