# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0028_auto_20160215_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
