# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 02:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0029_auto_20160215_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_car', models.BooleanField(default=False)),
                ('has_hose', models.BooleanField(default=False)),
                ('travel_distance', models.IntegerField(default=0)),
                ('vacuum_type', models.CharField(max_length=40)),
                ('availability', models.CharField(blank=True, max_length=40)),
                ('experience', models.CharField(blank=True, max_length=255)),
                ('baseUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
