# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0030_washer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washer',
            name='availability',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='washer',
            name='experience',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
