# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0031_auto_20160216_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washer',
            name='travel_distance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='washer',
            name='vacuum_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
