# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0032_auto_20160216_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washrequest',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='washrequest',
            name='status',
            field=models.CharField(default='Unconfirmed', max_length=40),
        ),
    ]
