# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0033_auto_20160217_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washrequest',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('cf', 'confirmed'), ('ip', 'in progress'), ('cp', 'completed'), ('cc', 'cancelled')], default='p', max_length=2),
        ),
    ]
