# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0034_auto_20160217_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('u', 'user'), ('e', 'washee'), ('r', 'washer')], default='u', max_length=1),
        ),
    ]
