# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0036_auto_20160217_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('washee', 'washee'), ('washer', 'washer')], default='user', max_length=10),
        ),
    ]
