# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0040_washrequest_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('wagon', 'Wagon'), ('suv', 'SUV'), ('van', 'Van')], default='Sedan', max_length=10),
        ),
    ]
