# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 02:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0042_auto_20160217_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('start_date', models.DateField(default=datetime.datetime(2016, 2, 22, 2, 47, 37, 231821, tzinfo=utc))),
                ('end_date', models.DateField(blank=True, null=True)),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='washrequest',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a.Promocode'),
        ),
    ]
