# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0043_auto_20160222_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
