# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0044_auto_20160222_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='max_usage',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
