# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0045_auto_20160222_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('%', 'percentage'), ('$', 'amount')], default='$', max_length=1),
        ),
    ]
