# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0047_washer_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaite Payment'), ('confirmed', 'Payment confirmed, arranging washer'), ('in progress', 'Washer assigned, wash in progress'), ('completed', 'Wash request completed'), ('cancelled', 'Wash request cancelled')], default='pending', max_length=20),
        ),
    ]
