# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0049_auto_20160223_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Payment Pending'), (2, 'Arranging Washer'), (3, 'Wash in Progress'), (4, 'Completed')], default=1),
        ),
    ]
