# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0050_auto_20160301_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Payment Pending'), (2, 'Arranging Washer'), (3, 'Wash in Progress'), (4, 'Completed'), (0, 'Cancelled')], default=1),
        ),
    ]
